### PR TITLE
Overhaul of finite-differences

### PR DESCRIPTION
**Pull request by jagot**

### CODE REVIEW

**Comment by jagot** [comment]
@dlfivefifty Julia 1.5 dies on Windows, for some reason (in addition to the non-fatal https://github.com/JuliaLang/julia/issues/37532 present on all platforms in 1.5, but fixed in 1.6). Do we care?

**Comment by dlfivefifty** [comment]
Can you try any `@test_broken` to see if there's a `StackOverflow` not being picked up?

**Comment by jagot** [comment]
Hmm, the only test marked as broken is this: https://github.com/JuliaApproximation/CompactBases.jl/blob/b5d36286f63f0484140d45a149e8576a6144873c/test/bsplines/splines.jl#L104

In any case, the crash occurs before any of the tests have even run: https://github.com/JuliaApproximation/CompactBases.jl/runs/2191648905?check_suite_focus=true#step:6:123

I wonder if this is related to the memory spike that @mortenpi sees in #38?
```
signal (22): SIGABRT
in expression starting at none:0
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
```

**Comment by dlfivefifty** [comment]
Yes it could be an out-of-memory issue, the Windows machine might not be as flexible. Perhaps just remove the Windows tests until someone complains?

**Comment by jagot** [comment]
Closes #40
Closes #42

**Pull request merged**
